--- # Gather ec2 facts from remote instances
- hosts: aws
  remote_user: ec2-user
  become: yes
  connection: ssh
  gather_facts: yes
  tasks:
  - name: gather the ec2 facts for running instances
    action: ec2_facts
  - name: display the instance type
    debug: msg='{{ ansible_ec2_instance_type }}'
